name: example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  
  flutter: 
    sdk: flutter
  get_storage: ^2.0.3
  http: ^0.13.5
  dio: ^5.0.0
  hexcolor: ^3.0.1
  google_fonts: ^4.0.3
  lottie: ^2.2.0
  font_awesome_flutter: ^10.4.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/img/
  uses-material-design: true

